// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAV10byX-ALe__Y7o0SsGkOA89PtZpXjY',
    appId: '1:895212383590:web:cfec58826e701eceb1eca7',
    messagingSenderId: '895212383590',
    projectId: 'crud-adec8',
    authDomain: 'crud-adec8.firebaseapp.com',
    storageBucket: 'crud-adec8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaoTQj8nMpxFpB3_WTTARVgjmC_MSwu3g',
    appId: '1:895212383590:android:354ecaf69c5631c6b1eca7',
    messagingSenderId: '895212383590',
    projectId: 'crud-adec8',
    storageBucket: 'crud-adec8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBksSidMOyTZVtNhJWp9D9nyJ_2mRRHdkw',
    appId: '1:895212383590:ios:14f31ac14b7e34adb1eca7',
    messagingSenderId: '895212383590',
    projectId: 'crud-adec8',
    storageBucket: 'crud-adec8.appspot.com',
    iosClientId: '895212383590-kngckbbk8ncmfstd8dacn7gr6mtd5cru.apps.googleusercontent.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBksSidMOyTZVtNhJWp9D9nyJ_2mRRHdkw',
    appId: '1:895212383590:ios:14f31ac14b7e34adb1eca7',
    messagingSenderId: '895212383590',
    projectId: 'crud-adec8',
    storageBucket: 'crud-adec8.appspot.com',
    iosClientId: '895212383590-kngckbbk8ncmfstd8dacn7gr6mtd5cru.apps.googleusercontent.com',
    iosBundleId: 'com.example.crud',
  );
}
